import type { SettingSearchEntry } from '@/utils/settingsSearch';

export const SETTINGS_GROUPS = {
    ACCOUNT: 'Account',
    APPEARANCE_INTERFACE: 'Appearance & Interface',
    AI_PROVIDERS_MODELS: 'AI Providers & Models',
    WORKFLOW_NODES: 'Workflow & Nodes',
    FILES_REPOSITORIES: 'Files & Repositories',
    TOOLS: 'Tools',
} as const;

export const SETTINGS_TABS = {
    PROFILE: 'Profile',
    SECURITY: 'Security',
    API_KEYS: 'API Keys',
    USAGE_LIMITS: 'Usage & Limits',
    ADMIN: 'Admin',
    THEME: 'Theme',
    CANVAS_STARTUP: 'Canvas Startup',
    CHAT_DISPLAY: 'Chat Display',
    MODEL_PICKER: 'Model Picker',
    INFERENCE_PROVIDERS: 'Inference Providers',
    DEFAULT_MODELS: 'Default Models',
    GENERATION_PARAMETERS: 'Generation Parameters',
    REASONING: 'Reasoning',
    GLOBAL_SYSTEM_PROMPTS: 'Global System Prompts',
    CONTEXT_WHEEL: 'Context Wheel',
    PROMPT_IMPROVER: 'Prompt Improver',
    PROMPT_TEMPLATES: 'Prompt Templates',
    ROUTING: 'Routing',
    PARALLELIZATION: 'Parallelization',
    CONTEXT_MERGER: 'Context Merger',
    GENERATION_HISTORY: 'Generation History',
    UPLOADS_FILE_MANAGER: 'Uploads & File Manager',
    DOCUMENT_PROCESSING: 'Document Processing',
    REPOSITORY_CONNECTIONS: 'Repository Connections',
    REPOSITORY_BEHAVIOR: 'Repository Behavior',
    TOOL_DEFAULTS: 'Tool Defaults',
    WEB_SEARCH: 'Web Search',
    LINK_EXTRACTION: 'Link Extraction',
    IMAGE_VIDEO_GENERATION: 'Image & Video Generation',
    VISUALISE: 'Visualise',
} as const;

export const SETTINGS_ENTRY = {
    profileIdentity: {
        id: 'profile.identity',
        group: SETTINGS_GROUPS.ACCOUNT,
        tab: SETTINGS_TABS.PROFILE,
        title: 'Profile',
        keywords: ['account', 'avatar', 'profile picture', 'username', 'email', 'plan badge'],
    },
    profileLogout: {
        id: 'profile.logout',
        group: SETTINGS_GROUPS.ACCOUNT,
        tab: SETTINGS_TABS.PROFILE,
        title: 'Log Out',
        keywords: ['logout', 'sign out', 'disconnect session'],
    },
    profileDeleteAccount: {
        id: 'profile.delete_account',
        group: SETTINGS_GROUPS.ACCOUNT,
        tab: SETTINGS_TABS.PROFILE,
        title: 'Delete Account',
        description: 'Permanently delete your account and all associated data.',
        keywords: ['remove account', 'close account', 'danger zone'],
    },
    securityPassword: {
        id: 'security.password',
        group: SETTINGS_GROUPS.ACCOUNT,
        tab: SETTINGS_TABS.SECURITY,
        title: 'Change Password',
        description: 'Use this option to change your password for local accounts.',
        keywords: ['password', 'old password', 'new password', 'confirm password'],
    },
    apiKeysOpenRouter: {
        id: 'api_keys.openrouter',
        group: SETTINGS_GROUPS.ACCOUNT,
        tab: SETTINGS_TABS.API_KEYS,
        title: 'OpenRouter API Key',
        description:
            'This key is used to authenticate your requests to the OpenRouter API. You can manage your keys on the OpenRouter website.',
        keywords: ['api key', 'key', 'open router', 'sk or v1'],
    },
    usageStorage: {
        id: 'usage.storage',
        group: SETTINGS_GROUPS.ACCOUNT,
        tab: SETTINGS_TABS.USAGE_LIMITS,
        title: 'Storage',
        description: 'File uploads and generated images stored in your account.',
        keywords: ['usage', 'limits', 'quota', 'storage breakdown', 'billing period'],
        options: ['generated images', 'videos', 'artefacts', 'artifacts', 'documents'],
    },
    usageQueries: {
        id: 'usage.queries',
        group: SETTINGS_GROUPS.ACCOUNT,
        tab: SETTINGS_TABS.USAGE_LIMITS,
        title: 'Query Usage',
        keywords: ['web search usage', 'link extraction usage', 'limits', 'quota'],
    },
    adminUsers: {
        id: 'admin.users',
        group: SETTINGS_GROUPS.ACCOUNT,
        tab: SETTINGS_TABS.ADMIN,
        title: 'User Management',
        description: 'Manage users, providers, plans, verification status, and account actions.',
        keywords: ['admin', 'delete users', 'plan', 'provider', 'verified', 'joined'],
    },
    appearanceTheme: {
        id: 'appearance.theme',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.THEME,
        title: 'Application Theme',
        description: 'Choose the application color theme or create your own custom palette.',
        keywords: ['appearance', 'theme', 'dark mode', 'light mode', 'custom theme', 'colors'],
        options: ['light', 'standard', 'github dark', 'oled', 'custom'],
    },
    appearanceAccentColor: {
        id: 'appearance.accent_color',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.THEME,
        title: 'Accent Color',
        description:
            'Choose the primary accent color used for buttons, highlights, and other key interface elements.',
        keywords: ['accent colour', 'brand color', 'primary color', 'ember glow'],
    },
    canvasOpenChat: {
        id: 'canvas.open_chat',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.CANVAS_STARTUP,
        title: 'Open Chat View On Canvas Creation',
        description:
            'When creating a new canvas, the chat view will be opened automatically. If disabled, the new canvas will start in canvas view.',
        keywords: ['canvas startup', 'general', 'chat view', 'canvas creation'],
    },
    canvasDefaultNodeType: {
        id: 'canvas.default_node_type',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.CANVAS_STARTUP,
        title: 'Default Node Type',
        description: 'The default node type to use when creating new nodes in chat view.',
        keywords: ['canvas startup', 'node type', 'new node'],
        options: ['Text to Text', 'Routing', 'Parallelization'],
    },
    chatThinkingPanels: {
        id: 'chat.thinking_panels',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.CHAT_DISPLAY,
        title: 'Always Open Thinking Panels',
        description:
            'When enabled, the thinking panels in the chat view will always be opened by default. If disabled, they will be collapsed by default.',
        keywords: ['chat display', 'thinking panels', 'reasoning panels'],
    },
    chatThinkingContext: {
        id: 'chat.thinking_context',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.CHAT_DISPLAY,
        title: 'Include Thinking In Context',
        description:
            'When enabled, previous model thinking process will be included in the context of the conversation. Recommended to be OFF for most users to reduce cost and avoid overwhelming the model.',
        keywords: ['chat display', 'thinking in context', 'reasoning context'],
    },
    chatMessageCollapsing: {
        id: 'chat.message_collapsing',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.CHAT_DISPLAY,
        title: 'Enable Message Collapsing',
        description:
            'When enabled, long user messages will be collapsed by default to improve readability. Users can expand or collapse messages as needed.',
        keywords: ['chat display', 'collapse messages', 'message collapse'],
    },
    modelPickerSort: {
        id: 'model_picker.sort',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.MODEL_PICKER,
        title: 'Sort Models By',
        description: 'Choose the default order for models displayed in selection dropdowns.',
        keywords: ['dropdown', 'model dropdown', 'model picker', 'sort'],
        options: ['Name (Ascending)', 'Name (Descending)', 'Date Added (Ascending)', 'Date Added (Descending)'],
    },
    modelPickerSections: {
        id: 'model_picker.sections',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.MODEL_PICKER,
        title: 'Dropdown Section Order',
        description:
            'Drag to reorder pinned models, subscription sections, and the all-models section. Disconnected subscription sections stay configurable here but remain hidden in the selector until connected.',
        keywords: ['model picker', 'dropdown order', 'section order'],
    },
    modelPickerHideFree: {
        id: 'model_picker.hide_free',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.MODEL_PICKER,
        title: 'Hide Free Models',
        description:
            'Enable this to hide free models from the model selection dropdowns. Pinned models will still be visible.',
        keywords: ['free models', 'hide free', 'model picker'],
    },
    modelPickerHidePaid: {
        id: 'model_picker.hide_paid',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.MODEL_PICKER,
        title: 'Hide Paid Models',
        description:
            'Enable this to hide paid models from model selection dropdowns. Pinned models will still be visible.',
        keywords: ['paid models', 'hide paid', 'model picker'],
    },
    modelPickerPinned: {
        id: 'model_picker.pinned',
        group: SETTINGS_GROUPS.APPEARANCE_INTERFACE,
        tab: SETTINGS_TABS.MODEL_PICKER,
        title: 'Pinned Models',
        description:
            'Pinned models always appear together in the pinned section at the top of the selector. Add your favorite models here, then drag cards to set their order.',
        keywords: ['favorites', 'favourites', 'starred models', 'model picker'],
    },
    providersClaude: {
        id: 'providers.claude',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.INFERENCE_PROVIDERS,
        title: 'Claude Agent',
        description: 'Anthropic subscription-backed models',
        keywords: ['providers', 'inference provider', 'anthropic', 'subscription', 'oauth credentials'],
    },
    providersGithubCopilot: {
        id: 'providers.github_copilot',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.INFERENCE_PROVIDERS,
        title: 'GitHub Copilot',
        description: 'Copilot subscription-backed models',
        keywords: ['providers', 'inference provider', 'github', 'copilot token'],
    },
    providersZAiCodingPlan: {
        id: 'providers.z_ai_coding_plan',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.INFERENCE_PROVIDERS,
        title: 'Z.AI Coding Plan',
        description: 'Z.AI Coding Plan endpoint models',
        keywords: ['providers', 'inference provider', 'z.ai', 'z ai', 'api key'],
    },
    providersGeminiCli: {
        id: 'providers.gemini_cli',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.INFERENCE_PROVIDERS,
        title: 'Gemini CLI',
        description: 'Google AI subscription via Gemini CLI',
        keywords: ['providers', 'inference provider', 'gemini cli', 'oauth credentials', 'google ai'],
    },
    providersOpenAICodex: {
        id: 'providers.openai_codex',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.INFERENCE_PROVIDERS,
        title: 'OpenAI Codex',
        description: 'OpenAI Codex subscription models',
        keywords: ['providers', 'inference provider', 'codex', 'openai', 'device code', 'oauth'],
    },
    providersOpenCodeGo: {
        id: 'providers.opencode_go',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.INFERENCE_PROVIDERS,
        title: 'OpenCode Go',
        description: 'OpenCode Go subscription models',
        keywords: ['providers', 'inference provider', 'opencode', 'opencode go', 'api key'],
    },
    modelsDefaultChat: {
        id: 'models.default_chat',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.DEFAULT_MODELS,
        title: 'Default Chat Model',
        description: 'The default model is used when creating a new chat or any block using a model.',
        keywords: ['default model', 'chat model'],
    },
    modelsRouting: {
        id: 'models.routing',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.DEFAULT_MODELS,
        title: 'Routing Model',
        description: 'The model used to choose routes for routing nodes.',
        keywords: ['default models', 'route model'],
    },
    modelsTitleGeneration: {
        id: 'models.title_generation',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.DEFAULT_MODELS,
        title: 'Title Generation Model',
        description: 'The model used to generate and regenerate canvas titles.',
        keywords: ['default models', 'title model', 'conversation title'],
    },
    modelsToolSelection: {
        id: 'models.tool_selection',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.DEFAULT_MODELS,
        title: 'Tool Selection Model',
        description: 'The model used when auto tool selection is enabled.',
        keywords: ['default models', 'auto tool selection', 'tool selection auto'],
    },
    generationMaxTokens: {
        id: 'generation.max_tokens',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.GENERATION_PARAMETERS,
        title: 'Max Tokens',
        description: 'The maximum number of tokens to generate in the chat response.',
        keywords: ['generation parameters', 'maximum tokens', 'token limit'],
    },
    generationTemperature: {
        id: 'generation.temperature',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.GENERATION_PARAMETERS,
        title: 'Temperature',
        description:
            'Controls randomness. Higher values make output more random, while lower values make it more deterministic.',
        keywords: ['generation parameters', 'creativity', 'randomness'],
    },
    generationTopP: {
        id: 'generation.top_p',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.GENERATION_PARAMETERS,
        title: 'Top P',
        description:
            'Controls nucleus sampling. The model considers tokens with a cumulative probability mass of this value.',
        keywords: ['generation parameters', 'nucleus sampling'],
    },
    generationTopK: {
        id: 'generation.top_k',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.GENERATION_PARAMETERS,
        title: 'Top K',
        description:
            'The model samples from the k most likely next tokens at each step. A lower k focuses on higher probability tokens.',
        keywords: ['generation parameters', 'sampling'],
    },
    generationFrequencyPenalty: {
        id: 'generation.frequency_penalty',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.GENERATION_PARAMETERS,
        title: 'Frequency Penalty',
        description:
            'Penalizes tokens based on their existing frequency, reducing the model tendency to repeat the same lines.',
        keywords: ['generation parameters', 'penalty', 'repeat lines'],
    },
    generationPresencePenalty: {
        id: 'generation.presence_penalty',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.GENERATION_PARAMETERS,
        title: 'Presence Penalty',
        description:
            'Penalizes tokens if they have already appeared in the text, encouraging the model to introduce new topics.',
        keywords: ['generation parameters', 'penalty', 'new topics'],
    },
    generationRepetitionPenalty: {
        id: 'generation.repetition_penalty',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.GENERATION_PARAMETERS,
        title: 'Repetition Penalty',
        description:
            'Helps prevent the model from repeating itself. It is a penalty applied to tokens that have been generated previously.',
        keywords: ['generation parameters', 'penalty', 'repeat tokens'],
    },
    reasoningExclude: {
        id: 'reasoning.exclude',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.REASONING,
        title: 'Exclude Reasoning',
        description:
            'Exclude reasoning tokens from the model response. The model will still reason internally, but it will not be included in the final response.',
        keywords: ['reasoning', 'hide reasoning', 'exclude thoughts'],
    },
    reasoningEffort: {
        id: 'reasoning.effort',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.REASONING,
        title: 'Reasoning Effort',
        description: 'Controls how much effort the model will put into reasoning before generating a response.',
        keywords: ['reasoning', 'thinking effort'],
    },
    systemPromptsGlobal: {
        id: 'system_prompts.global',
        group: SETTINGS_GROUPS.AI_PROVIDERS_MODELS,
        tab: SETTINGS_TABS.GLOBAL_SYSTEM_PROMPTS,
        title: 'Global System Prompts',
        description:
            'Manage the global system prompts that are prepended to your conversations. You can reorder them by dragging, enable or disable them, and edit their content. The order here determines the order of injection.',
        keywords: ['system prompt', 'prompt name', 'enable prompt', 'disable prompt', 'read only', 'editable'],
    },
    blocksContextWheel: {
        id: 'blocks.context_wheel',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.CONTEXT_WHEEL,
        title: 'Context Wheel',
        description:
            'Define the options available in the wheel menu when using Ctrl+Hover on a generator node handle. Click a slot to configure its main block and quick options.',
        keywords: ['blocks', 'workflow', 'wheel menu', 'ctrl hover', 'quick options', 'wheel slots'],
    },
    blocksPromptImproverOverride: {
        id: 'blocks.prompt_improver.override',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.PROMPT_IMPROVER,
        title: 'Override Prompt Improver Model',
        description:
            'Force Prompt Improver to use a specific model for audit, clarification, and improvement instead of the selected downstream target model.',
        keywords: ['prompt improver', 'override prompt improver model', 'improve prompt'],
    },
    blocksPromptImproverModel: {
        id: 'blocks.prompt_improver.model',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.PROMPT_IMPROVER,
        title: 'Prompt Improver Model',
        description: 'This model is used only when the override above is enabled.',
        keywords: ['prompt improver', 'override prompt improver model', 'improve prompt'],
    },
    blocksPromptTemplates: {
        id: 'blocks.prompt_templates',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.PROMPT_TEMPLATES,
        title: 'Prompt Templates',
        description:
            'Create reusable prompt structures with variables to standardize your workflow nodes. Reorder templates via drag-and-drop.',
        keywords: ['template marketplace', 'create template', 'edit template', 'variables', 'fork and edit'],
    },
    blocksRouting: {
        id: 'blocks.routing',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.ROUTING,
        title: 'Routing Configuration',
        description:
            'Create and manage route groups to intelligently direct user prompts to the most suitable model based on predefined rules. Each route can have its own model, custom prompt, and behavior. You can set a default group and create specialized groups for different tasks like coding, writing, or analysis.',
        keywords: ['route groups', 'default route group', 'route models', 'custom prompt', 'duplicate route', 'rename route'],
    },
    blocksParallelizationAggregatorModel: {
        id: 'blocks.parallelization.aggregator_model',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.PARALLELIZATION,
        title: 'Aggregator Model',
        description:
            'The default model used to aggregate the results of the parallelized blocks. This model will process the aggregated data and return the final result.',
        keywords: ['parallel models', 'parallelization', 'aggregator model', 'aggregator prompt'],
    },
    blocksParallelizationAggregatorPrompt: {
        id: 'blocks.parallelization.aggregator_prompt',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.PARALLELIZATION,
        title: 'Aggregator Prompt',
        description:
            'This prompt is used to aggregate the results of the parallelized blocks. It is sent to the model after all blocks have been processed. You can use this prompt to summarize the results or to ask the model to perform additional processing on the aggregated data.',
        keywords: ['parallel models', 'parallelization', 'aggregator model', 'aggregator prompt'],
    },
    blocksParallelizationModels: {
        id: 'blocks.parallelization.models',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.PARALLELIZATION,
        title: 'Parallelization models',
        description:
            'The default models used to process the blocks in parallel. Each model will process its own block and return the result. The results will be aggregated by the aggregator model.',
        keywords: ['parallel models', 'parallelization', 'aggregator model', 'aggregator prompt'],
    },
    blocksContextMergerMode: {
        id: 'blocks.context_merger.mode',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.CONTEXT_MERGER,
        title: 'Merger Mode',
        description: 'Select the default merging strategy for new Context Merger nodes.',
        keywords: ['context merger', 'merger mode', 'full', 'summary', 'last n'],
        options: ['full', 'summary', 'last_n'],
    },
    blocksContextMergerLastN: {
        id: 'blocks.context_merger.last_n',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.CONTEXT_MERGER,
        title: '"Last N" Value',
        description:
            'Set the default number of recent conversation turns to include when using the "Last N" mode.',
        keywords: ['context merger', 'last n', 'recent conversation turns'],
    },
    blocksContextMergerSummarizerModel: {
        id: 'blocks.context_merger.summarizer_model',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.CONTEXT_MERGER,
        title: 'Summarizer Model',
        description:
            'Choose the model used for summarizing branches in "Summary" mode. A powerful, but relatively cheap model is recommended for a cost effective balance between performance and expense.',
        keywords: ['context merger', 'summary mode', 'summarizer model'],
    },
    blocksContextMergerIncludeUserMessages: {
        id: 'blocks.context_merger.include_user_messages',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.CONTEXT_MERGER,
        title: 'Include User Messages',
        description:
            'Set whether user messages should be included by default when merging context. Disabling may result in less relevant context. Enabling is generally recommended but may increase token usage.',
        keywords: ['context merger', 'include user messages', 'user context'],
    },
    generationHistorySavedEntries: {
        id: 'blocks.generation_history.saved_entries',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.GENERATION_HISTORY,
        title: 'Saved Generation History',
        description:
            'Set how many previous generations are kept per text, routing, or parallelization node. Max 100.',
        keywords: [
            'generation history',
            'history limit',
            'saved generations',
            'node history',
        ],
    },
    generationHistoryCloseOnRestore: {
        id: 'blocks.generation_history.close_on_restore',
        group: SETTINGS_GROUPS.WORKFLOW_NODES,
        tab: SETTINGS_TABS.GENERATION_HISTORY,
        title: 'Close After Restore',
        description:
            'Close the generation history popover automatically after restoring a previous generation.',
        keywords: [
            'generation history',
            'close modal',
            'close popover',
            'restore generation',
            'history modal',
        ],
    },
    filesUploadFolder: {
        id: 'files.upload_folder',
        group: SETTINGS_GROUPS.FILES_REPOSITORIES,
        tab: SETTINGS_TABS.UPLOADS_FILE_MANAGER,
        title: 'Default Upload Folder',
        description:
            'Specify the default folder where uploaded files will be stored when uploading from devices. Folder will be created if it does not exist.',
        keywords: ['uploads', 'file manager', 'attachment', 'upload folder'],
    },
    filesDefaultSort: {
        id: 'files.default_sort',
        group: SETTINGS_GROUPS.FILES_REPOSITORIES,
        tab: SETTINGS_TABS.UPLOADS_FILE_MANAGER,
        title: 'Default Sort',
        description: 'Choose the sort order used when the file manager opens.',
        keywords: ['file manager', 'default sort', 'sort order'],
        options: [
            'Name A-Z',
            'Name Z-A',
            'Date newest first',
            'Date oldest first',
            'Size largest first',
            'Size smallest first',
            'Type A-Z',
            'Type Z-A',
        ],
    },
    filesDefaultView: {
        id: 'files.default_view',
        group: SETTINGS_GROUPS.FILES_REPOSITORIES,
        tab: SETTINGS_TABS.UPLOADS_FILE_MANAGER,
        title: 'Default View',
        description: 'Choose the layout used when the file manager opens.',
        keywords: ['file manager', 'default view', 'layout'],
        options: ['Grid', 'Gallery', 'List', 'Compact tiles', 'Larger previews', 'Dense rows'],
    },
    filesRememberLastSort: {
        id: 'files.remember_last_sort',
        group: SETTINGS_GROUPS.FILES_REPOSITORIES,
        tab: SETTINGS_TABS.UPLOADS_FILE_MANAGER,
        title: 'Remember Last Sort',
        description: 'Save manual sort changes in this browser and use them instead of the default.',
        keywords: ['file manager', 'remember sort', 'remember last sort'],
    },
    filesRememberLastView: {
        id: 'files.remember_last_view',
        group: SETTINGS_GROUPS.FILES_REPOSITORIES,
        tab: SETTINGS_TABS.UPLOADS_FILE_MANAGER,
        title: 'Remember Last View',
        description: 'Save manual view changes in this browser and use them instead of the default.',
        keywords: ['file manager', 'remember view', 'remember last view'],
    },
    filesPdfEngine: {
        id: 'files.pdf_engine',
        group: SETTINGS_GROUPS.FILES_REPOSITORIES,
        tab: SETTINGS_TABS.DOCUMENT_PROCESSING,
        title: 'PDF Engine',
        description: 'Choose the default PDF engine for document processing.',
        keywords: ['document processing', 'documents', 'pdf processing'],
        options: ['default', 'mistral ocr', 'mistral-ocr', 'pdf text', 'pdf-text', 'native'],
    },
    repositoriesGithub: {
        id: 'repositories.github',
        group: SETTINGS_GROUPS.FILES_REPOSITORIES,
        tab: SETTINGS_TABS.REPOSITORY_CONNECTIONS,
        title: 'GitHub App Connection',
        description: 'Connect your GitHub account to enable repository access for use in blocks.',
        keywords: ['github', 'repository connections', 'repo connection'],
    },
    repositoriesGitlab: {
        id: 'repositories.gitlab',
        group: SETTINGS_GROUPS.FILES_REPOSITORIES,
        tab: SETTINGS_TABS.REPOSITORY_CONNECTIONS,
        title: 'GitLab Connection',
        description:
            'Connect your GitLab account using a Personal Access Token and an SSH key to access your private repositories.',
        keywords: ['gitlab', 'repository connections', 'personal access token', 'pat', 'ssh private key', 'instance url'],
    },
    repositoriesAutoPull: {
        id: 'repositories.auto_pull',
        group: SETTINGS_GROUPS.FILES_REPOSITORIES,
        tab: SETTINGS_TABS.REPOSITORY_BEHAVIOR,
        title: 'Auto Pull',
        description:
            'Automatically pull the latest changes from the repository. This is triggered when a block using the repository is executed or when you open the file selection.',
        keywords: ['repository behavior', 'git pull', 'sync repository'],
    },
    toolsAutoSelection: {
        id: 'tools.auto_selection',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.TOOL_DEFAULTS,
        title: 'Default Auto Tool Selection',
        description: 'Enable auto tool selection by default for new text-to-text and routing nodes.',
        keywords: ['tool defaults', 'auto tools', 'automatic tool selection'],
    },
    toolsSelectedTools: {
        id: 'tools.selected_tools',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.TOOL_DEFAULTS,
        title: 'Default Selected Tools',
        description: 'Choose which tools are selected by default when you start a new conversation.',
        keywords: ['tool defaults', 'selected tools', 'available tools'],
        options: ['web search', 'link extraction', 'media gen', 'execute code', 'visualise', 'ask user'],
    },
    toolsWebSearchResults: {
        id: 'tools.web_search.results',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.WEB_SEARCH,
        title: 'Number Of Search Results',
        description:
            'The number of search results to return for each query. Recommended range is 1-10 with 5 being the default recommended value.',
        keywords: ['web search', 'search result count', 'number results'],
    },
    toolsWebSearchApiKey: {
        id: 'tools.web_search.api_key',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.WEB_SEARCH,
        title: 'Custom Search JSON API Key',
        description:
            'Provide your own Google Custom Search API key to use your personal search quota. Provides 100 search queries per day for free. Additional requests cost $5 per 1000 queries. Requests made with this key will not be counted towards the system overall query limit.',
        keywords: ['web search', 'google search api key', 'api key', 'json api key'],
    },
    toolsWebSearchForceKey: {
        id: 'tools.web_search.force_key',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.WEB_SEARCH,
        title: 'Force User API Key',
        description: 'If a custom API key is set, force its usage over the system custom web search engine.',
        keywords: ['web search', 'force api key', 'force user key'],
    },
    toolsWebSearchIgnoredSites: {
        id: 'tools.web_search.ignored_sites',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.WEB_SEARCH,
        title: 'Sites to Ignore',
        description: 'A list of websites to exclude from search results. Enter one domain per line.',
        keywords: ['web search', 'sites to ignore', 'ignored sites', 'exclude websites'],
    },
    toolsWebSearchPreferredSites: {
        id: 'tools.web_search.preferred_sites',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.WEB_SEARCH,
        title: 'Sites to Prefer',
        description: 'A list of websites to prioritize in search results. Enter one domain per line.',
        keywords: ['web search', 'sites to prefer', 'preferred sites', 'prioritize websites'],
    },
    toolsLinkExtraction: {
        id: 'tools.link_extraction',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.LINK_EXTRACTION,
        title: 'Max Content Length',
        description:
            'The maximum length of content in characters to return when extracting from a link. Default is 100,000.',
        keywords: ['link extraction', 'content length', 'extract links'],
    },
    toolsDefaultImageModel: {
        id: 'tools.image.default_model',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.IMAGE_VIDEO_GENERATION,
        title: 'Default Image Model',
        description:
            'The default image generation model to use for generating images. You can override this setting on a per-node basis in the graph editor.',
        keywords: ['image generation', 'media generation', 'default image model'],
    },
    toolsDefaultVideoModel: {
        id: 'tools.video.default_model',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.IMAGE_VIDEO_GENERATION,
        title: 'Default Video Model',
        description:
            'The default video generation model to use for generating videos. You can override this setting on a per-node basis in the graph editor.',
        keywords: ['video generation', 'media generation', 'default video model'],
    },
    toolsVisualiseMermaidOutput: {
        id: 'tools.visualise.mermaid_output',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.VISUALISE,
        title: 'Enable Mermaid Output',
        description: 'Allow the Visualise tool to generate Mermaid diagrams.',
        keywords: ['visualize', 'visualise', 'diagram', 'chart', 'mermaid'],
    },
    toolsVisualiseMermaidRetry: {
        id: 'tools.visualise.mermaid_retry',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.VISUALISE,
        title: 'Enable Mermaid Retry',
        description: 'Retry Mermaid generation with parser feedback when backend validation fails.',
        keywords: ['visualise', 'mermaid retry', 'max mermaid retry', 'retry diagram'],
    },
    toolsVisualiseMaxMermaidRetry: {
        id: 'tools.visualise.max_mermaid_retry',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.VISUALISE,
        title: 'Max Mermaid Retry',
        description: 'Number of repair attempts after the initial Mermaid generation. Default is 3.',
        keywords: ['visualise', 'mermaid retry', 'max mermaid retry', 'retry diagram'],
    },
    toolsVisualiseSvgOutput: {
        id: 'tools.visualise.svg_output',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.VISUALISE,
        title: 'Enable SVG Output',
        description: 'Allow the Visualise tool to generate SVG visuals.',
        keywords: ['visualize', 'visualise', 'diagram', 'chart', 'svg'],
    },
    toolsVisualiseHtmlOutput: {
        id: 'tools.visualise.html_output',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.VISUALISE,
        title: 'Enable HTML Output',
        description: 'Allow the Visualise tool to generate HTML artifacts and interactive widgets.',
        keywords: ['visualize', 'visualise', 'diagram', 'chart', 'html', 'widget'],
    },
    toolsVisualiseMermaidModel: {
        id: 'tools.visualise.mermaid_model',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.VISUALISE,
        title: 'Mermaid Model',
        description: 'Used when the Visualise tool is called with output_mode="mermaid".',
        keywords: ['visualise', 'mermaid model'],
    },
    toolsVisualiseStandardModel: {
        id: 'tools.visualise.standard_model',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.VISUALISE,
        title: 'Standard Model',
        description: 'Used for normal diagrams, charts, and explainers generated by the Visualise tool.',
        keywords: ['visualise', 'standard model', 'diagram', 'chart'],
    },
    toolsVisualiseExpertModel: {
        id: 'tools.visualise.expert_model',
        group: SETTINGS_GROUPS.TOOLS,
        tab: SETTINGS_TABS.VISUALISE,
        title: 'Expert Model',
        description:
            'Used when the Visualise tool is called with difficulty="expert" for more demanding visual representations.',
        keywords: ['visualise', 'expert model', 'difficult diagram', 'advanced chart'],
    },
} satisfies Record<string, SettingSearchEntry>;

export const SETTINGS_SEARCH_ENTRIES = Object.values(SETTINGS_ENTRY);
