<script lang="ts" setup>
const settingsStore = useSettingsStore();
const { toolsVisualiseSettings } = storeToRefs(settingsStore);
</script>

<template>
    <div class="flex flex-col">
        <div class="flex items-center justify-between py-6">
            <div class="max-w-2xl">
                <h3 class="text-soft-silk font-semibold">Standard Model</h3>
                <p class="text-stone-gray/80 mt-1 text-sm">
                    Used for normal diagrams, charts, and explainers generated by the Visualise
                    tool.
                </p>
            </div>
            <div class="ml-6 shrink-0">
                <UiModelsSelect
                    id="visualise-standard-model"
                    :model="toolsVisualiseSettings.standardModel"
                    :set-model="
                        (model: string) => {
                            toolsVisualiseSettings.standardModel = model;
                        }
                    "
                    :disabled="false"
                    to="right"
                    from="bottom"
                    variant="grey"
                    class="h-10 w-[20rem]"
                    hide-tool
                />
            </div>
        </div>

        <div class="flex items-center justify-between py-6">
            <div class="max-w-2xl">
                <h3 class="text-soft-silk font-semibold">Expert Model</h3>
                <p class="text-stone-gray/80 mt-1 text-sm">
                    Used when the Visualise tool is called with `difficulty="expert"` for more
                    demanding visual representations.
                </p>
            </div>
            <div class="ml-6 shrink-0">
                <UiModelsSelect
                    id="visualise-expert-model"
                    :model="toolsVisualiseSettings.expertModel"
                    :set-model="
                        (model: string) => {
                            toolsVisualiseSettings.expertModel = model;
                        }
                    "
                    :disabled="false"
                    to="right"
                    from="bottom"
                    variant="grey"
                    class="h-10 w-[20rem]"
                    hide-tool
                />
            </div>
        </div>
    </div>
</template>

<style scoped></style>
