from models.chatDTO import EffortEnum
from models.usersDTO import (
    SettingsDTO,
    GeneralSettings,
    AccountSettings,
    ModelsSettings,
    ModelsDropdownSettings,
    BlockSettings,
    BlockParallelizationSettings,
    BlockParallelizationAggregatorSettings,
    BlockParallelizationModelSettings,
    ModelsDropdownSortBy,
)
from const.prompts import GLOBAL_SYSTEM_PROMPT, PARALLELIZATION_AGGREGATOR_PROMPT

DEFAULT_SETTINGS = SettingsDTO(
    general=GeneralSettings(
        openChatViewOnNewCanvas=True,
        alwaysThinkingDisclosures=False,
        includeThinkingInContext=False,
    ),
    account=AccountSettings(
        openRouterApiKey=None,
    ),
    models=ModelsSettings(
        defaultModel="google/gemini-2.5-flash-preview-05-20",
        excludeReasoning=False,
        globalSystemPrompt=GLOBAL_SYSTEM_PROMPT,
        reasoningEffort=EffortEnum.MEDIUM,
        maxTokens=None,
        temperature=0.7,
        topP=1.0,
        topK=40,
        frequencyPenalty=0.0,
        presencePenalty=0.0,
        repetitionPenalty=1.0,
    ),
    modelsDropdown=ModelsDropdownSettings(
        sortBy=ModelsDropdownSortBy.DATE_DESC,
        hideFreeModels=False,
        hidePaidModels=False,
        pinnedModels=[],
    ),
    block=BlockSettings(
        wheel=[
            "parallelization",
            "text-to-text",
            "text-to-text-attachement",
        ]
    ),
    blockParallelization=BlockParallelizationSettings(
        models=[
            BlockParallelizationModelSettings(
                model="google/gemini-2.5-flash-preview-05-20"
            ),
            BlockParallelizationModelSettings(model="openai/gpt-4o-mini"),
        ],
        aggregator=BlockParallelizationAggregatorSettings(
            prompt=PARALLELIZATION_AGGREGATOR_PROMPT,
            model="google/gemini-2.5-flash-preview-05-20:thinking",
        ),
    ),
)
