services:
  ui:
    build: 
      context: ..
      dockerfile: docker/ui.Dockerfile
    container_name: ${NAME}_ui
    ports:
      - "${NITRO_PORT}:${NITRO_PORT}"
    depends_on:
      db:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    environment:
        - ENV=${ENV}
        - NITRO_PORT=${NITRO_PORT}
        - NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL}
        - NUXT_API_INTERNAL_BASE_URL=${NUXT_API_INTERNAL_BASE_URL}
        - NUXT_PUBLIC_IS_OAUTH_DISABLED=${NUXT_PUBLIC_IS_OAUTH_DISABLED}
        - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
        - NUXT_OAUTH_GITHUB_CLIENT_ID=${NUXT_OAUTH_GITHUB_CLIENT_ID}
        - NUXT_OAUTH_GITHUB_CLIENT_SECRET=${NUXT_OAUTH_GITHUB_CLIENT_SECRET}
        - NUXT_OAUTH_GOOGLE_CLIENT_ID=${NUXT_OAUTH_GOOGLE_CLIENT_ID}
        - NUXT_OAUTH_GOOGLE_CLIENT_SECRET=${NUXT_OAUTH_GOOGLE_CLIENT_SECRET}
        - NUXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
        - NUXT_PUBLIC_VERSION=${NUXT_PUBLIC_VERSION}

  api:
    build: 
      context: ..
      dockerfile: docker/api.Dockerfile
    container_name: ${NAME}_api
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "${API_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    volumes:
      - user_files:/app/data/user_files
      - cloned_repos:/app/data/cloned_repos
    environment:
      - ENV=${ENV}
      - USERPASS=${USERPASS}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - ALLOW_CORS_ORIGINS=${ALLOW_CORS_ORIGINS}
      - API_PORT=${API_PORT}
      - MASTER_OPEN_ROUTER_API_KEY=${MASTER_OPEN_ROUTER_API_KEY}
      - DATABASE_ECHO=${DATABASE_ECHO}
      - BACKEND_SECRET=${BACKEND_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_HOST=${NEO4J_HOST}
      - NEO4J_BOLT_PORT=${NEO4J_BOLT_PORT}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
      - DATABASE_POOL_SIZE=${DATABASE_POOL_SIZE}
      - DATABASE_MAX_OVERFLOW=${DATABASE_MAX_OVERFLOW}

  db:
    image: postgres:17
    container_name: ${NAME}_pg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../api/app/database/pg/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h ${POSTGRES_HOST} -p ${POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - -p
      - ${POSTGRES_PORT}
      - -c
      - shared_buffers=${POSTGRES_SHARED_BUFFERS}
      - -c
      - effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE}
      - -c
      - work_mem=${POSTGRES_WORK_MEM}
      - -c
      - maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM}
      - -c
      - random_page_cost=${POSTGRES_RANDOM_PAGE_COST}
      - -c
      - max_worker_processes=${POSTGRES_MAX_WORKER_PROCESSES}
      - -c
      - max_parallel_workers_per_gather=${POSTGRES_MAX_PARALLEL_WORKERS_PER_GATHER}
      - -c
      - max_parallel_workers=${POSTGRES_MAX_PARALLEL_WORKERS}
      - -c
      - log_min_duration_statement=${POSTGRES_LOG_MIN_DURATION_STATEMENT}
      - -c
      - log_lock_waits=${POSTGRES_LOG_LOCK_WAITS}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  neo4j:
    image: neo4j:5
    container_name: ${NAME}_neo4j
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_server_http_listen__address=${NEO4J_HTTP_ADDRESS}
      - NEO4J_server_bolt_listen__address=${NEO4J_BOLT_ADDRESS}
    healthcheck:
      test: ["CMD", "cypher-shell", "-a", "neo4j://localhost:${NEO4J_BOLT_PORT}", "-u", "${NEO4J_USER}", "-p", "${NEO4J_PASSWORD}", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user_files:
  cloned_repos:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  sentry_data: {}