import { defineConfig } from "oxlint";

export default defineConfig({
    categories: {
        correctness: "error",
    },
    plugins: ["eslint", "typescript", "unicorn", "oxc", "vue"],
    ignorePatterns: [
        ".agent/**",
        ".agents/**",
        ".claude/**",
        ".codex/**",
        ".continue/**",
        ".cursor/**",
        ".gemini/**",
        ".nuxt/**",
        ".opencode/**",
        ".output/**",
        ".pi/**",
        ".roo/**",
        ".windsurf/**",
        "node_modules/**",
        "test-results/**",
        "tools/oxlint/anti-slop/**",
        "**/useFileIcons.ts",
        "**/vue-cropperjs.d.ts",
        "**/vue-virtual-scroller.d.ts",
    ],
    jsPlugins: [
        { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
    ],
    rules: {
        "anti-slop/no-chained-type-assertions": "error",
        "anti-slop/no-conditional-empty-object-spread": "error",
        "anti-slop/no-known-value-widening": "error",
        "anti-slop/no-module-mocking": "error",
        "anti-slop/no-object-parameters": "error",
        "anti-slop/no-reflect-apply": "error",
        "anti-slop/no-reflect-get": "error",
        "anti-slop/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
        "anti-slop/no-shape-in-symbol-names": "error",
        "anti-slop/no-unknown-parameters": "error",
        "anti-slop/no-unknown-returns": "error",
        "anti-slop/no-unknown-type-aliases": "error",
        "anti-slop/no-unsafe-dictionary-type": "error",
        "anti-slop/no-widen-then-assert": "error",
        "anti-slop/require-safety-comment-for-type-assertion": "error",
    },
});
