x-common-env: &common-env
  env_file:
    - .env.prod

services:
  api:
    <<: *common-env
    build: 
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: meridian_api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - neo4j

  db:
    <<: *common-env
    image: postgres:17
    container_name: meridian_pg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/database/pg/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  neo4j:
    # <<: *common-env
    image: neo4j:5
    container_name: meridian_neo4j
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/OTDXzz0gIdl5cZeJJeNh
volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: