[tool.black]
line-length = 100
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
    | _build
    | buck-out
    | build
    | dist
    | app/data/cloned_repos
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip = ["venv", "app/data/cloned_repos"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
exclude = ["venv", "app/data/cloned_repos"]
